version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mrruser
      POSTGRES_PASSWORD: mrruser
    ports:
      - 5432:5432

  spring:
    image: mokhovav/meeting_room_reservation
    restart: always
    ports:
      - 8080:8080

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080